# Try-Catch Except문

In [1]:
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='12345678',
                             database='classicmodels',
                             cursorclass=pymysql.cursors.DictCursor)

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

In [8]:
numerator = 10 
denominator = 0
result = numerator / denominator
a = 1
b = 2
print(a+b)

ZeroDivisionError: division by zero

In [11]:
try: 
    numerator = 10 
    denominator = 0
    result = numerator / denominator
except ZeroDivisionError:
    print("Error: Cannot Divide By Zero!")
else:
    print("The result is:", result)
finally: 
    print("This will always execute.")
    a = 1
    b = 2
    print(a+b)

temp_list = [1, 2, 3]
print(temp_list)

Error: Cannot Divide By Zero!
This will always execute.
3
[1, 2, 3]

In [14]:
try: 
    numerator = 10 
    denominator = int(input("숫자 입력해주세요: "))
    result = numerator / denominator
except ZeroDivisionError:
    print("Error: Cannot Divide By Zero!")
else:
    print("The result is:", result)
finally: 
    print("This will always execute.")
    a = 1
    b = 2
    print(a+b)

temp_list = [1, 2, 3]
print(temp_list)

숫자 입력해주세요:  0

Error: Cannot Divide By Zero!
This will always execute.
3
[1, 2, 3]

# Step 1. Connect to Server
- MySQL localhost 서버와 연결하는 코드

In [ ]:
from mysql import connector 
PASSWORD = '12345678'
# PASSWORD = input("DB Password를 입력해주세요...")

try: 
    # Database 연동하는 코드 작성
    with connector.connect(
        host = 'localhost', # 회사에서는 ip 주소 입력
        user = 'root', # 회사에서 아이디 부여
        password = PASSWORD
    ) as database:
        print(f'데이터베이스 객체(object): {database}')
except connector.Error as e:
    print(e)
finally: 
    print("무조건 실행해야 함")

# Step 2. 데이터베이스 생성

In [1]:
PASSWORD = '12345678'

try: 
    # Database 연동하는 코드 작성
    with connector.connect(
        host = 'localhost', # 회사에서는 ip 주소 입력
        user = 'root', # 회사에서 아이디 부여
        password = PASSWORD
    ) as database:
        print(f'데이터베이스 객체(object): {database}')
        print("DATABASE 생성 ---------")
        delete_db = "DROP DATABASE book_ratings;" # SQL 코드 작성
        create_db = "CREATE DATABASE book_ratings;"

        with database.cursor() as cursor: 
            # cursor.execute(create_db)

            # 현재 접속한 서버의 데이터베이스를 확인
            show_existing_db = "SHOW DATABASES;"
            cursor.execute(show_existing_db)
            # 반복문 활용
            for db in cursor:
                print(db)


except connector.Error as e:
    print(e)
finally: 
    print("무조건 실행해야 함")

무조건 실행해야 함

NameError: name 'connector' is not defined

## SQL서버 + DB에 직접 접속하는 방법

In [25]:
from mysql import connector 
PASSWORD = '12345678'
DATABASE_NAME = 'book_ratings'

try: 
    # Database 연동하는 코드 작성
    with connector.connect(
        host = 'localhost', # 회사에서는 ip 주소 입력
        user = 'root', # 회사에서 아이디 부여
        password = PASSWORD, 
        database = DATABASE_NAME # 기존 접속하는 방법과 Key 차이점
    ) as database:
        print(f'데이터베이스 객체(object): {database}')
except connector.Error as e:
    print(e)
finally: 
    print("무조건 실행해야 함")

데이터베이스 객체(object): <mysql.connector.connection_cext.CMySQLConnection object at 0x000001BE4CAF7EF0>
무조건 실행해야 함

# Step 3. 테이블 생성
- 쿼리가 길어지면, multi-line 문자열로 저장

In [27]:
create_books_table = """
CREATE TABLE books(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100),
    author VARCHAR(100),
    genre VARCHAR(100),
    release_year YEAR(4)
);
"""

In [35]:
from mysql import connector 
PASSWORD = '12345678'
DATABASE_NAME = 'classicmodels'

try: 
    # Database 연동하는 코드 작성
    with connector.connect(
        host = 'localhost', # 회사에서는 ip 주소 입력
        user = 'root', # 회사에서 아이디 부여
        password = PASSWORD, 
        database = DATABASE_NAME # 기존 접속하는 방법과 Key 차이점
    ) as database:
        print(f'데이터베이스 객체(object): {database}')
        print("DATABASE 생성 ---------")

        with database.cursor() as cursor: 
            # cursor.execute(create_books_table) # 테이블 생성하는 코드
            # 커밋
            # database.commit() # MySQL 서버에 반영함

            # 쿼리, DESCRIBE books 
            query1 = "DESCRIBE orders;"
            cursor.execute(query1)
            books_schema = cursor.fetchall()
            for column in books_schema:
                print(column)
            
except connector.Error as e:
    print(e)
finally: 
    print("무조건 실행해야 함")

데이터베이스 객체(object): <mysql.connector.connection_cext.CMySQLConnection object at 0x000001BE4CC39370>
DATABASE 생성 ---------
('orderNumber', 'int', 'NO', 'PRI', None, '')
('orderDate', 'date', 'NO', '', None, '')
('requiredDate', 'date', 'NO', '', None, '')
('shippedDate', 'date', 'YES', '', None, '')
('status', 'varchar(15)', 'NO', '', None, '')
('comments', 'text', 'YES', '', None, '')
('customerNumber', 'int', 'NO', 'MUL', None, '')
무조건 실행해야 함

# Step 4. 데이터 추가

In [34]:
# INSERT SINGLE RECORD
insert_single_record = "INSERT INTO books (id, title, author, genre, release_year)\
    VALUES (%s, %s, %s, %s, %s)"
single_record = (
    "1", "Choose Yourself! Be Happy, Make Millions, Live the Dream", "James Altucher", "self-help", "2013"
    )

try: 
    # Connect to existing database
    with connector.connect(
        host = "localhost",
        user = "root",
        password = PASSWORD,
        database = "book_ratings"
    ) as existing_database:
        
        # Create cursor object
        with existing_database.cursor() as cursor:
            cursor.execute(insert_single_record, single_record)
            existing_database.commit()
        
except connector.Error as e: 
    print(e)

# INSERT MULTIPLE RECORDS
insert_multiple_records = "INSERT INTO books (id, title, author, genre, release_year)\
    VALUES (%s, %s, %s, %s, %s)"
multiple_records = [
    (
        "2", 
        "Skip the Line: The 10,000 Experiments Rule and Other Surprising Advice for Reaching Your Goals",
        "James Altucher",
        "self-help",
        "2021"        
    ),
    (
        "3",
        "The Power of No: Because One Little Word Can Bring Health, Abundance, and Happiness",
        "James Altucher",
        "self-help",
        "2014"
    ),
    (
        "4",
        "The 48 Laws of Power",
        "Robert Greene",
        "self-help",
        "1998"
    ),
    (
        "5",
        "Mastery",
        "Robert Greene",
        "self-help",
        "2012"
    ),
    (
        "6",
        "The Art of Seduction",
        "Robert Greene",
        "self-help",
        "2001"
    ),
]

try: 
    # Connect to existing database
    with connector.connect(
        host = "localhost",
        user = "root",
        password = PASSWORD,
        database = "book_ratings"
    ) as existing_database:
        
        # Create cursor object
        with existing_database.cursor() as cursor:
            cursor.executemany(insert_multiple_records, multiple_records)
            existing_database.commit()
        
except connector.Error as e: 
    print(e)

# Step 5. Select 데이터

In [36]:
from mysql import connector 
PASSWORD = '12345678'
DATABASE_NAME = 'book_ratings'

try: 
    # Database 연동하는 코드 작성
    with connector.connect(
        host = 'localhost', # 회사에서는 ip 주소 입력
        user = 'root', # 회사에서 아이디 부여
        password = PASSWORD, 
        database = DATABASE_NAME # 기존 접속하는 방법과 Key 차이점
    ) as database:
        print(f'데이터베이스 객체(object): {database}')
        print("DATABASE 생성 ---------")

        with database.cursor() as cursor: 
            # cursor.execute(create_books_table) # 테이블 생성하는 코드
            # 커밋
            # database.commit() # MySQL 서버에 반영함

            # 쿼리, DESCRIBE books 
            query1 = "SELECT * FROM books;"
            cursor.execute(query1)
            books_schema = cursor.fetchall()
            for column in books_schema:
                print(column)
            
except connector.Error as e:
    print(e)
finally: 
    print("무조건 실행해야 함")

데이터베이스 객체(object): <mysql.connector.connection_cext.CMySQLConnection object at 0x000001BE4CC387D0>
DATABASE 생성 ---------
(1, 'Choose Yourself! Be Happy, Make Millions, Live the Dream', 'James Altucher', 'self-help', 2013)
(2, 'Skip the Line: The 10,000 Experiments Rule and Other Surprising Advice for Reaching Your Goals', 'James Altucher', 'self-help', 2021)
(3, 'The Power of No: Because One Little Word Can Bring Health, Abundance, and Happiness', 'James Altucher', 'self-help', 2014)
(4, 'The 48 Laws of Power', 'Robert Greene', 'self-help', 1998)
(5, 'Mastery', 'Robert Greene', 'self-help', 2012)
(6, 'The Art of Seduction', 'Robert Greene', 'self-help', 2001)
무조건 실행해야 함

# Step 6. pandas 데이터프레임으로 데이터 가져오기

In [40]:
import mysql.connector as connector
import pandas as pd

PASSWORD = '12345678'  
def fetch_data_to_dataframe(query, database=None):
    try: 

        with connector.connect(
            host="localhost",
            user="root",
            password=PASSWORD,
            database=database
        ) as existing_database:
            
            with existing_database.cursor() as cursor:
                cursor.execute(query)

                # 테이블의 컬럼명만 추출하는 코드 ==> List 형태로 변형
                column_names = [i[0] for i in cursor.description]

                # Values, 데이터값
                returned_data = cursor.fetchall()

                # pandas 데이터프레임으로 만듬
                df = pd.DataFrame(returned_data, columns=column_names)
                return df
    
    except connector.Error as e: 
        print(e)
        return None

query_specific_cols = "SELECT author, release_year FROM books"
df_specific_cols = fetch_data_to_dataframe(query_specific_cols, "book_ratings")
df_specific_cols

           author  release_year
0  James Altucher          2013
1  James Altucher          2021
2  James Altucher          2014
3   Robert Greene          1998
4   Robert Greene          2012
5   Robert Greene          2001

In [38]:
df_specific_cols

           author  release_year
0  James Altucher          2013
1  James Altucher          2021
2  James Altucher          2014
3   Robert Greene          1998
4   Robert Greene          2012
5   Robert Greene          2001

In [42]:
query_specific_cols = """
SELECT 
	MAX(주문건수), MIN(주문건수), AVG(주문건수) AS 평균주문건수
FROM (
	SELECT 
		ordernumber, count(ordernumber) AS 주문건수
	FROM orderdetails
	GROUP BY ordernumber
) A
;
"""

orders = fetch_data_to_dataframe(query_specific_cols, "classicmodels")
orders

   MAX(주문건수)  MIN(주문건수)  평균주문건수
0         18          1  9.1902